CREATE PROC FI_SP_IncBeneficiario
    @NOME          VARCHAR (50),
    @CPF           VARCHAR (14),
	@IDCLIENTE     BIGINT
AS
BEGIN

    SELECT @CPF = REPLACE(REPLACE(REPLACE(REPLACE(@CPF, '.', ''), '-', ''), '_', ''), ' ', '')

	INSERT INTO BENEFICIARIOS (NOME, CPF, IDCLIENTE) 
	VALUES (@NOME, @CPF,@IDCLIENTE)

	SELECT SCOPE_IDENTITY()
END